services:
  mongo-db:
    image: mongo
    hostname: mongo-db
    container_name: db-mongo
    ports:
       - "27017:27017"
    networks:
      - fiware_network
    command: --nojournal --bind_ip_all
    volumes:
      - mongo-data:/data/db
      - mongo-data:/data/configdb
  orion:
    image: fiware/orion
    container_name: orion
    links:
      - mongo-db
    ports:
      - "1026:1026"
    command: -dbhost mongo-db
    networks:
      - fiware_network
    volumes:
      - orion-data:/var/lib/orion
  draco:
    image: ging/fiware-draco:latest
    container_name: draco
    environment:
      - NIFI_WEB_HTTPS_PORT=9090
      - SINGLE_USER_CREDENTIALS_USERNAME=admin
      - SINGLE_USER_CREDENTIALS_PASSWORD=pass1234567890
      - DRACO_DATABASE_DRIVER_CLASS_NAME=com.mongodb.MongoClient
      - DRACO_DATABASE_URL=mongodb://mongo-db:27017/
    ports:
      - "9090:9090"
      - "5050:5050"
    depends_on:
      - mongo-db
    networks:
      - fiware_network
    volumes:
      - draco-data:/opt/nifi/nifi-current/conf
      - draco-data:/opt/nifi/nifi-current/logs
      - draco-data:/opt/nifi/nifi-current/state
      - draco-data:/opt/nifi/nifi-current/provenance_repository
      - draco-data:/opt/nifi/nifi-current/content_repository
      - draco-data:/opt/nifi/nifi-current/database_repository
      - draco-data:/opt/nifi/nifi-current/flowfile_repository
    healthcheck:
      test: curl --fail -s https://draco:9090/nifi-api/system-diagnostics || exit 1
  iot-agent:
    image: quay.io/fiware/iotagent-ul:latest
    hostname: iot-agent
    container_name: fiware-iot-agent
    depends_on:
        - mongo-db
    networks:
      - fiware_network
    expose:
        - "4041"
        - "7896"
    ports:
        - "4041:4041"
        - "7896:7896"
    environment:
        - IOTA_CB_HOST=orion
        - IOTA_CB_PORT=1026
        - IOTA_NORTH_PORT=4041
        - IOTA_REGISTRY_TYPE=mongodb
        - IOTA_LOG_LEVEL=DEBUG
        - IOTA_TIMESTAMP=true
        - IOTA_CB_NGSI_VERSION=v2
        - IOTA_AUTOCAST=true
        - IOTA_MONGO_HOST=mongo-db
        - IOTA_MONGO_PORT=27017
        - IOTA_MONGO_DB=iotagentul
        - IOTA_HTTP_PORT=7896
        - IOTA_PROVIDER_URL=http://iot-agent:4041
    volumes:
      - iotagent-data:/var/lib/iotagent
  backend:
    container_name: backend
    build: back/.
    ports:
      - "3000:3000"    
    environment:
      - BACK_PORT=3000
      - MODO_PERSISTENCIA=MONGO
      - MONGO_HOST=mongo-db
      - DATABASE_URL=mongodb://mongo-db:27017/
      - MONGO_BASE=sth_respirar
      - ORION_HOST=orion
    networks:
      - fiware_network
  frontend:
    container_name: frontend
    build: front/.
    ports:
      - "8080:8080"
    environment:
      - BACK_HOST=backend
      - BACK_PORT=3000
      #- BACK_URL=http://backend:3000
      - BACK_URL=http://localhost:3000
      
    networks:
      - fiware_network
networks:
  fiware_network:
    driver: bridge
volumes:
  mongo-data:
  draco-data:
  orion-data:
  iotagent-data: