# version: "3"

# services:
#   web:
#     container_name: exampleapp
#     restart: always
#     build: .
#     ports: 
#       - "8080:3000"
#     links:
#       - mongo
#     volumes:
#       - .:/usr/src/app
#   mongo:
#     container_name: myMongoDataBase
#     image: mongo
#     ports:
#       - "27018:27017"
#     logging:
#       driver: none
services:
   mongo:
    container_name: myMongoDataBase
    image: mongo
    command: --nojournal
    ports:
       - "27018:27017"
    logging:
     driver: none
   orion:
    image: fiware/orion
    links:
      - mongo
    ports:
      - "1026:1026"
    command: -dbhost mongo
   backend:
    build: back/.
    ports:
      - "3000:3000"    
   frontend:
    build: front/.
    ports:
      - "8080:8080"    