services:
  mongo-db:
    image: mongo
    hostname: mongo-db
    container_name: db-mongo
    ports:
       - "27017:27017"
    networks:
      - fiware_network
    command: --nojournal --bind_ip_all
  orion:
    image: fiware/orion
    links:
      - mongo-db
    ports:
      - "1026:1026"
    command: -dbhost mongo-db
    networks:
      - fiware_network
  draco:
    image: ging/fiware-draco:latest
    container_name: draco
    environment:
      - NIFI_WEB_HTTPS_PORT=9090
      - SINGLE_USER_CREDENTIALS_USERNAME=admin
      - SINGLE_USER_CREDENTIALS_PASSWORD=pass1234567890
      #- DRACO_DATABASE_DRIVER_CLASS_NAME=com.mongodb.MongoClient
      #- DRACO_DATABASE_URL=mongodb://172.18.0.2:27017/
    ports:
      - "9090:9090"
      - "5050:5050"
    depends_on:
      - mongo-db
    networks:
      - fiware_network
    healthcheck:
      test: curl --fail -s https://localhost:9090/nifi-api/system-diagnostics || exit 1
  #mongodb-draco:
    # image: mongo
    # container_name: mongodb-draco
    # command: --nojournal
    # restart: always
    # ports:
    #   - "27018:27018"
    # logging:
    #  driver: none
  # mysql:
  #   image: mysql:5.7.22
  #   container_name: mysql
  #   command: --default-authentication-plugin=mysql_native_password
  #   restart: always
  #   environment:
  #     MYSQL_ROOT_PASSWORD: example
  #   ports:
  #     - "3306:3306"
  # backend:
  #   build: back/.
  #   ports:
  #     - "3000:3000"    
  # frontend:
  #   build: front/.
  #   ports:
  #     - "8080:8080"
  iot-agent:
    image: quay.io/fiware/iotagent-ul:latest
    hostname: iot-agent
    container_name: fiware-iot-agent
    depends_on:
        - mongo-db
    networks:
      - fiware_network
    expose:
        - "4041"
        - "7896"
    ports:
        - "4041:4041"
        - "7896:7896"
    environment:
        - IOTA_CB_HOST=orion
        - IOTA_CB_PORT=1026
        - IOTA_NORTH_PORT=4041
        - IOTA_REGISTRY_TYPE=mongodb
        - IOTA_LOG_LEVEL=DEBUG
        - IOTA_TIMESTAMP=true
        - IOTA_CB_NGSI_VERSION=v2
        - IOTA_AUTOCAST=true
        - IOTA_MONGO_HOST=mongo-db
        - IOTA_MONGO_PORT=27017
        - IOTA_MONGO_DB=iotagentul
        - IOTA_HTTP_PORT=7896
        - IOTA_PROVIDER_URL=http://iot-agent:4041
networks:
  fiware_network: