# version: "3"

# services:
#   web:
#     container_name: exampleapp
#     restart: always
#     build: .
#     ports: 
#       - "8080:3000"
#     links:
#       - mongo
#     volumes:
#       - .:/usr/src/app
#   mongo:
#     container_name: myMongoDataBase
#     image: mongo
#     ports:
#       - "27018:27017"
#     logging:
#       driver: none
services:
  mongo:
    container_name: myMongoDataBase
    image: mongo
    command: --nojournal
    ports:
       - "27018:27017"
    logging:
     driver: none
  orion:
    image: fiware/orion
    links:
      - mongo
    ports:
      - "1026:1026"
    command: -dbhost mongo
  # backend:
  #   build: back/.
  #   ports:
  #     - "3000:3000"    
  # frontend:
  #   build: front/.
  #   ports:
  #     - "8080:8080"
  iot-agent:
    image: quay.io/fiware/iotagent-ul:latest
    hostname: iot-agent
    container_name: fiware-iot-agent
    depends_on:
        - mongo
    networks:
        - default
    expose:
        - "4041"
        - "7896"
    ports:
        - "4041:4041"
        - "7896:7896"
    environment:
        - IOTA_CB_HOST=orion
        - IOTA_CB_PORT=1026
        - IOTA_NORTH_PORT=4041
        - IOTA_REGISTRY_TYPE=mongodb
        - IOTA_LOG_LEVEL=DEBUG
        - IOTA_TIMESTAMP=true
        - IOTA_CB_NGSI_VERSION=v2
        - IOTA_AUTOCAST=true
        - IOTA_MONGO_HOST=mongo
        - IOTA_MONGO_PORT=27017
        - IOTA_MONGO_DB=iotagentul
        - IOTA_HTTP_PORT=7896
        - IOTA_PROVIDER_URL=http://iot-agent:4041